MEDICAL_GRAPH_NODES = [
    {"name": "Diagnosis", "thai": "การวินิจฉัย", "kind": "concept", "definition": "กระบวนการระบุโรคจากอาการ ประวัติ และผลตรวจ"},
    {"name": "Prognosis", "thai": "พยากรณ์โรค", "kind": "concept", "definition": "การคาดการณ์แนวโน้มและการหายของโรค"},
    {"name": "Symptom", "thai": "อาการ", "kind": "concept", "definition": "สิ่งที่ผู้ป่วยรู้สึกเอง เช่น ปวดศีรษะ คลื่นไส้"},
    {"name": "Sign", "thai": "อาการแสดง", "kind": "concept", "definition": "สิ่งที่ผู้ตรวจพบได้ เช่น ไข้ บวม ความดันโลหิตสูง"},
    {"name": "Acute", "thai": "เฉียบพลัน", "kind": "concept", "definition": "เกิดเร็วและเป็นระยะสั้น"},
    {"name": "Chronic", "thai": "เรื้อรัง", "kind": "concept", "definition": "เป็นระยะยาว"},
    {"name": "Benign", "thai": "ไม่ร้ายแรง", "kind": "concept", "definition": "ไม่ลุกลามแบบมะเร็ง"},
    {"name": "Malignant", "thai": "ร้ายแรง", "kind": "concept", "definition": "เป็นมะเร็งหรือลุกลาม"},
    {"name": "Fever", "thai": "ไข้", "kind": "sign", "definition": "อาการแสดงที่วัดอุณหภูมิได้สูง"},
    {"name": "Cough", "thai": "ไอ", "kind": "symptom", "definition": "อาการทางเดินหายใจที่พบบ่อย"},
    {"name": "Hyper-", "thai": "มากกว่าปกติ", "kind": "prefix", "definition": "อุปสรรคหมายถึงสูงหรือมากเกิน"},
    {"name": "Hypo-", "thai": "น้อยกว่าปกติ", "kind": "prefix", "definition": "อุปสรรคหมายถึงต่ำหรือน้อยเกิน"},
    {"name": "Brady-", "thai": "ช้า", "kind": "prefix", "definition": "อุปสรรคหมายถึงช้า"},
    {"name": "Tachy-", "thai": "เร็ว", "kind": "prefix", "definition": "อุปสรรคหมายถึงเร็ว"},
    {"name": "Hypertension", "thai": "ความดันโลหิตสูง", "kind": "disease", "definition": "ความดันโลหิตสูง เพิ่มความเสี่ยงโรคหัวใจและหลอดเลือดสมอง"},
    {"name": "Hypoglycemia", "thai": "น้ำตาลในเลือดต่ำ", "kind": "disease", "definition": "ภาวะน้ำตาลในเลือดต่ำ"},
    {"name": "Bradycardia", "thai": "หัวใจเต้นช้า", "kind": "disease", "definition": "หัวใจเต้นช้ากว่าปกติ"},
    {"name": "Tachycardia", "thai": "หัวใจเต้นเร็ว", "kind": "disease", "definition": "หัวใจเต้นเร็วกว่าปกติ"},
    {"name": "Anemia", "thai": "ภาวะซีด", "kind": "disease", "definition": "เม็ดเลือดแดงหรือฮีโมโกลบินต่ำ"},
    {"name": "-itis", "thai": "การอักเสบ", "kind": "suffix", "definition": "ปัจจัยหมายถึงการอักเสบ"},
    {"name": "Tonsillitis", "thai": "ต่อมทอนซิลอักเสบ", "kind": "disease", "definition": "ต่อมทอนซิลอักเสบ"},
    {"name": "Appendectomy", "thai": "การตัดไส้ติ่ง", "kind": "procedure", "definition": "ผ่าตัดนำไส้ติ่งออก"},
    {"name": "Endoscopy", "thai": "การส่องกล้อง", "kind": "procedure", "definition": "ส่องตรวจทางเดินอาหาร"},
    {"name": "Neuralgia", "thai": "ปวดตามเส้นประสาท", "kind": "symptom", "definition": "อาการปวดตามเส้นประสาท"},
    {"name": "Blood pressure", "thai": "ความดันโลหิต", "kind": "concept", "definition": "ค่า systolic บน diastolic ล่าง เช่น 120/80 mmHg"},
    {"name": "Myocardial infarction", "thai": "กล้ามเนื้อหัวใจตาย", "kind": "disease", "definition": "หัวใจวายจากการขาดเลือด"},
    {"name": "Arrhythmia", "thai": "หัวใจเต้นผิดจังหวะ", "kind": "disease", "definition": "ภาวะหัวใจเต้นผิดจังหวะ"},
    {"name": "Atherosclerosis", "thai": "หลอดเลือดแดงแข็ง", "kind": "disease", "definition": "หลอดเลือดแดงแข็งจากคราบไขมัน"},
    {"name": "Chest pain", "thai": "แน่นอก", "kind": "symptom", "definition": "สัญญาณอันตรายของโรคหัวใจ"},
    {"name": "Stroke", "thai": "โรคหลอดเลือดสมอง", "kind": "disease", "definition": "ภาวะที่ความดันสูงเรื้อรังเพิ่มความเสี่ยง"},
    {"name": "Diabetes", "thai": "เบาหวาน", "kind": "disease", "definition": "โรคประจำตัวที่เกี่ยวกับน้ำตาลในเลือด"},
    {"name": "Dyspnea", "thai": "หายใจลำบาก", "kind": "symptom", "definition": "อาการหายใจลำบาก"},
    {"name": "Tachypnea", "thai": "หายใจเร็ว", "kind": "sign", "definition": "อัตราการหายใจเร็ว"},
    {"name": "Hypoxia", "thai": "ออกซิเจนในเนื้อเยื่อต่ำ", "kind": "concept", "definition": "ออกซิเจนในเนื้อเยื่อต่ำ"},
    {"name": "Hypoxemia", "thai": "ออกซิเจนในเลือดต่ำ", "kind": "concept", "definition": "ออกซิเจนในเลือดต่ำ"},
    {"name": "Pneumonia", "thai": "ปอดอักเสบ", "kind": "disease", "definition": "ปอดอักเสบจากเชื้อ"},
    {"name": "Asthma", "thai": "หอบหืด", "kind": "disease", "definition": "ทางเดินหายใจตีบตัว"},
    {"name": "NPO", "thai": "งดน้ำงดอาหาร", "kind": "abbreviation", "definition": "คำสั่งงดน้ำงดอาหาร"},
    {"name": "PRN", "thai": "ให้เมื่อมีอาการ", "kind": "abbreviation", "definition": "ให้ยาเมื่อมีอาการ"},
    {"name": "BID", "thai": "วันละ 2 ครั้ง", "kind": "abbreviation", "definition": "ความถี่การให้ยาวันละ 2 ครั้ง"},
    {"name": "TID", "thai": "วันละ 3 ครั้ง", "kind": "abbreviation", "definition": "ความถี่การให้ยาวันละ 3 ครั้ง"},
    {"name": "IV", "thai": "ฉีดเข้าหลอดเลือดดำ", "kind": "abbreviation", "definition": "ทางให้ยาเข้าหลอดเลือดดำ"},
    {"name": "IM", "thai": "ฉีดเข้ากล้ามเนื้อ", "kind": "abbreviation", "definition": "ทางให้ยาเข้ากล้ามเนื้อ"},
]

MEDICAL_GRAPH_RELATIONSHIPS = [
    {"from": "Diagnosis", "to": "Symptom", "type": "USES", "label": "ใช้ข้อมูลจาก"},
    {"from": "Diagnosis", "to": "Sign", "type": "USES", "label": "ใช้ข้อมูลจาก"},
    {"from": "Prognosis", "to": "Diagnosis", "type": "FOLLOWS", "label": "ต่อจากการวินิจฉัย"},
    {"from": "Acute", "to": "Chronic", "type": "OPPOSES", "label": "ตรงข้ามกับ"},
    {"from": "Benign", "to": "Malignant", "type": "OPPOSES", "label": "ตรงข้ามกับ"},
    {"from": "Fever", "to": "Sign", "type": "IS_A", "label": "เป็นชนิดของ"},
    {"from": "Cough", "to": "Symptom", "type": "IS_A", "label": "เป็นชนิดของ"},
    {"from": "Hyper-", "to": "Hypertension", "type": "FORMS", "label": "ประกอบเป็น"},
    {"from": "Hypo-", "to": "Hypoglycemia", "type": "FORMS", "label": "ประกอบเป็น"},
    {"from": "Brady-", "to": "Bradycardia", "type": "FORMS", "label": "ประกอบเป็น"},
    {"from": "Tachy-", "to": "Tachycardia", "type": "FORMS", "label": "ประกอบเป็น"},
    {"from": "Tachy-", "to": "Tachypnea", "type": "FORMS", "label": "ประกอบเป็น"},
    {"from": "-itis", "to": "Tonsillitis", "type": "FORMS", "label": "ประกอบเป็น"},
    {"from": "Hypertension", "to": "Blood pressure", "type": "IS_A", "label": "เป็นภาวะของ"},
    {"from": "Hypertension", "to": "Stroke", "type": "INCREASES_RISK", "label": "เพิ่มความเสี่ยง"},
    {"from": "Hypertension", "to": "Myocardial infarction", "type": "INCREASES_RISK", "label": "เพิ่มความเสี่ยง"},
    {"from": "Atherosclerosis", "to": "Myocardial infarction", "type": "CAN_CAUSE", "label": "อาจทำให้เกิด"},
    {"from": "Myocardial infarction", "to": "Chest pain", "type": "HAS_SYMPTOM", "label": "มีอาการ"},
    {"from": "Arrhythmia", "to": "Tachycardia", "type": "INCLUDES", "label": "รวมถึง"},
    {"from": "Arrhythmia", "to": "Bradycardia", "type": "INCLUDES", "label": "รวมถึง"},
    {"from": "Hypoglycemia", "to": "Diabetes", "type": "RELATED_TO", "label": "เกี่ยวข้องกับ"},
    {"from": "Dyspnea", "to": "Asthma", "type": "SEEN_IN", "label": "พบบ่อยใน"},
    {"from": "Dyspnea", "to": "Pneumonia", "type": "SEEN_IN", "label": "พบบ่อยใน"},
    {"from": "Hypoxia", "to": "Hypoxemia", "type": "RELATED_TO", "label": "เกี่ยวข้องกับ"},
    {"from": "Tachypnea", "to": "Pneumonia", "type": "SEEN_IN", "label": "พบบ่อยใน"},
    {"from": "BID", "to": "TID", "type": "RELATED_TO", "label": "เป็นคำบอกความถี่เช่นเดียวกับ"},
    {"from": "IV", "to": "IM", "type": "RELATED_TO", "label": "เป็นทางให้ยาเช่นเดียวกับ"},
]
